apiVersion: v1
kind: Secret
metadata:
  name: ajouevent-secret
  namespace: ajouevent
type: Opaque
data:
  # MySQL root 패스워드 (base64 encoded)
  mysql-root-password: YWpvdWV2ZW50MjAyNCE=  # ajouevent2024!
  mysql-password: YWpvdWV2ZW50MjAyNCE=       # ajouevent2024!
  
  # Redis 패스워드 (필요시)
  redis-password: ""
  
  # JWT Secret (base64 encoded)
  jwt-secret: YWpvdWV2ZW50LWp3dC1zZWNyZXQtMjAyNA==  # ajouevent-jwt-secret-2024 