apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: ajouevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: ajouevent/crawler:fixed
        imagePullPolicy: Never
        env:
        - name: DB_IP
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: mysql-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: mysql-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: mysql-database
        - name: DB_USER
          value: "ajouevent"
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: ajouevent-secret
              key: mysql-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: redis-port
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: timezone
        - name: CRAWLING_PERIOD
          value: "60"
        - name: WEBHOOK_ENDPOINT
          value: "http://backend-service:8080/api/crawling/webhook"
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: logs
          mountPath: /workspace/logs
      volumes:
      - name: logs
        emptyDir: {}
 