apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ajouevent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ajouevent/backend:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: spring-profiles-active
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DATABASE)?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
        - name: SPRING_DATASOURCE_USERNAME
          value: "ajouevent"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ajouevent-secret
              key: mysql-password
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: redis-host
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: redis-port
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: mysql-host
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: mysql-port
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: mysql-database
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ajouevent-secret
              key: jwt-secret
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: timezone
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: regcred 