apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ajouevent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ajouevent/backend:fixed
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        # 기본 Spring 설정
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: spring-profiles-active
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: timezone
        
        # 데이터베이스 설정
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/ajouevent?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
        - name: SPRING_DATASOURCE_USERNAME
          value: "ajouevent"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ajouevent-secret
              key: mysql-password
        
        # Redis 설정
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: redis-host
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ajouevent-config
              key: redis-port
        
        - name: SPRING_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ajouevent-secret
              key: jwt-secret
        
        envFrom:
        - configMapRef:
            name: backend-config
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: firebase-config
          mountPath: /app/firebase
          readOnly: true
      
      volumes:
      - name: logs
        emptyDir: {}
      - name: firebase-config
        configMap:
          name: firebase-config
 